# Generated by Django 5.1.3 on 2024-11-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pings', '0003_alter_ping_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pings', to='pings.tag'),
        ),
    ]
